### PR TITLE
noninteractive mode + other fixes

### LINKED ISSUE #13: Don’t delete pinned toots
Toots pinned to people’s profiles shouldn’t be deleted, regardless of how old they are.

### PR DESCRIPTION
**Pull request by cdzombak**
Recently I made a bunch of changes when setting this up on one of my own servers. This is a messy commit — hacked together in a hurry — so feel free to reject it.

• includes PR #16, fix for #15 
• add non-interactive mode (#17)
• allow storing configuration/credentials in a custom file (#4, though I didn't change the default path, for backwards compatibility)
• allow printing version number
• don't delete pinned posts - includes the relevant commit (https://github.com/ThomasLeister/mastopurge/pull/18/commits/420f10fa7b9adcb35bf33ff11a27c0a1ed87f431) from PR #18 (fixes #13)
• add dry-run mode
• add quiet mode, for cron jobs & similar use cases

All the noninteractive mode/config file changes should be backwards compatible; running mastopurge as before will work the same.

### CODE REVIEW

**Comment by ThomasLeister** [comment]
Hi @cdzombak 

thanks for all the work! Currently I have very limited time to review patches here and do some Mastopurge development, but I hope I can have a detailed look on what you did, soon :-)

**Comment by brortao** [comment]
This is very neat! But FYI I noticed that the `build_static.sh` script no longer works now that `api.go` is in its own file.

**Comment by cdzombak** [comment]
> This is very neat! But FYI I noticed that the `build_static.sh` script no longer works now that `api.go` is in its own file.

Ah, I wasn't using that to build the program. Fixed in https://github.com/ThomasLeister/mastopurge/pull/19/commits/006bb950db4b8551ca95df0049061ea6a2bd0d60

**Comment by ThomasLeister** [comment]
Your features / changes have made it into release 1.2.0 ! Thank you! I made some changes and obviously Github is not able to track that ... therefore this PR is obsolete :)

**Pull request closed without merging**
